# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/NexysVideoHarness.runs/synth_1/NexysVideoHarness.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 2
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tsbg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/NexysVideoHarness.cache/wt [current_project]
set_property parent.project_path /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/NexysVideoHarness.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part_repo_paths {/bwrcq/C/jameslukas/chipyard/fpga/fpga-shells/xilinx/nexys_video/board} [current_project]
set_property board_part digilentinc.com:nexys_video:part0:1.1 [current_project]
set_property ip_repo_paths /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip [current_project]
update_ip_catalog
set_property ip_output_repo /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/NexysVideoHarness.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AMOALU.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AXI4AsyncCrossingSink.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AXI4AsyncCrossingSource.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AXI4Deinterleaver.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AXI4IdIndexer.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AXI4UserYanker.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Arbiter2_Valid_PTWReq.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Arbiter3_LLWB.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueue.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSink_AXI4BundleAR.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSink_AXI4BundleAW.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSink_AXI4BundleB.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSink_AXI4BundleR.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSink_AXI4BundleW.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSink_Phit.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSource_AXI4BundleAR.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSource_AXI4BundleAW.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSource_AXI4BundleB.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSource_AXI4BundleR.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSource_AXI4BundleW.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncQueueSource_Phit.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetReg.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetRegVec_w13_i0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetRegVec_w1_i0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetRegVec_w1_i1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetRegVec_w2_i0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetSynchronizerPrimitiveShiftReg_d3_i0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetSynchronizerShiftReg_w1_d3_i0_4.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncResetSynchronizerShiftReg_w4_d3_i0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AsyncValidSync.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/BTB.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/BankBinder.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/BreakpointUnit.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/BroadcastFilter.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/BundleBridgeNexus_UInt1_1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/CLINT.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/CLINTClockSinkDomain.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/CSRFile.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ChipTop.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ChipyardPRCICtrlClockSinkDomain.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockCrossingReg_w32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockCrossingReg_w6.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockCrossingReg_w61.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockCrossingReg_w71.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockCrossingReg_w73.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockGroupAggregator_allClocks.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockGroupAsyncResetCoercer.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockGroupCombiner.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockGroupResetSynchronizer.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ClockGroup_1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/CoherenceManagerWrapper.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/CompareRecFN.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DCache.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DCacheDataArray.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DecoupledSerialPhy.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DigitalTop.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRawFN_small_e11_s53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRawFN_small_e5_s11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRawFN_small_e8_s24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRecFMToRaw_small_e11_s53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRecFMToRaw_small_e5_s11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRecFMToRaw_small_e8_s24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRecFM_small_e11_s53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRecFM_small_e5_s11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/DivSqrtRecFM_small_e8_s24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ErrorDeviceWrapper.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FPToFP.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FPToInt.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FPU.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FPUDecoder.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FPUFMAPipe_l3_f16.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FPUFMAPipe_l3_f32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FPUFMAPipe_l4_f64.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FixedClockBroadcast_2.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FixedClockBroadcast_4.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FixedClockBroadcast_5.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FlitToPhit_f32_p32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/FrontBus.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Frontend.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/GenericDeserializer_TLBeatw10_f32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/GenericDeserializer_TLBeatw67_f32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/GenericDeserializer_TLBeatw87_f32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/GenericDeserializer_TLBeatw88_f32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/GenericSerializer_TLBeatw67_f32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/GenericSerializer_TLBeatw87_f32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/HellaCacheArbiter.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/IBuf.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ICache.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/INToRecFN_i64_e11_s53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/INToRecFN_i64_e5_s11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/INToRecFN_i64_e8_s24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ITLB.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/IntSyncCrossingSource_n1x1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/IntSyncCrossingSource_n1x2.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/IntSyncSyncCrossingSink_n1x1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/IntSyncSyncCrossingSink_n1x2.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/IntToFP.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/IntXbar_i4_o1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MaxPeriodFibonacciLFSR.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MemoryBus.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNPipe_l2_e11_s53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNPipe_l2_e5_s11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNPipe_l2_e8_s24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNToRaw_postMul_e11_s53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNToRaw_postMul_e5_s11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNToRaw_postMul_e8_s24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNToRaw_preMul_e11_s53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNToRaw_preMul_e5_s11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulAddRecFNToRaw_preMul_e8_s24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/MulDiv.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/OptimizationBarrier_PTE.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/OptimizationBarrier_TLBEntryData.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/OptimizationBarrier_UInt.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PLICClockSinkDomain.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PMAChecker.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PMPChecker_s2.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PMPChecker_s3.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PTW.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PeripheryBus_cbus.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PeripheryBus_pbus.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PhitArbiter_p32_f32_n5.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PhitDemux_p32_f32_n5.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PhitToFlit_p32_f32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PlusArgTimeout.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ProbePicker.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue1_AXI4BundleARW.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue1_AXI4BundleW.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue1_BundleMap.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue1_RegMapperInput_i23_m8.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue1_TLBundleA_a14d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue1_TLBundleD_a64d64s8k8z8c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a13d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a14d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a21d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a28d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a28d64s8k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a32d64s2k2z4c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a32d64s4k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a32d64s4k2z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleA_a32d64s5k2z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleB_a32d64s2k2z4c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleC_a32d64s2k2z4c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a13d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a14d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a21d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a28d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a28d64s8k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a32d64s2k2z4c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a32d64s4k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a32d64s4k2z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleD_a32d64s5k2z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue2_TLBundleE_a32d64s2k2z4c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue8_AXI4BundleR.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue8_Flit.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue8_TLBroadcastData.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Queue8_UInt8.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RVCExpander.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RecFNToIN_e11_s53_i32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RecFNToIN_e11_s53_i64.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RecFNToRecFN.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RecFNToRecFN_1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Repeater_TLBundleA_a13d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Repeater_TLBundleA_a17d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Repeater_TLBundleA_a21d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Repeater_TLBundleA_a26d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Repeater_TLBundleA_a28d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Repeater_TLBundleA_a28d64s8k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ResetCatchAndSync_d3.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ResetWrangler.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/Rocket.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RocketALU.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RocketTile.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundAnyRawFNToRecFN_ie11_is53_oe5_os11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundAnyRawFNToRecFN_ie11_is53_oe8_os24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundAnyRawFNToRecFN_ie11_is55_oe11_os53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundAnyRawFNToRecFN_ie5_is13_oe5_os11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundAnyRawFNToRecFN_ie7_is64_oe11_os53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundAnyRawFNToRecFN_ie7_is64_oe5_os11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundAnyRawFNToRecFN_ie7_is64_oe8_os24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundAnyRawFNToRecFN_ie8_is26_oe8_os24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundRawFNToRecFN_e11_s53.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundRawFNToRecFN_e5_s11.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/RoundRawFNToRecFN_e8_s24.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ScratchpadBank.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/SerialTL0ClockSinkDomain.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/SerialWidthAdapter.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/SerialWidthAggregator.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/SerialWidthSlicer.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ShiftQueue.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/SystemBus.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLAFromBeat_serial_tl_0_a64d64s8k8z8c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLAtomicAutomata_cbus.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLAtomicAutomata_pbus.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBFromBeat_serial_tl_0_a64d64s8k8z8c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBToBeat_serial_tl_0_a64d64s8k8z8c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBroadcast.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBroadcastTracker.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBroadcastTracker_1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBroadcastTracker_2.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBroadcastTracker_3.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a13d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a14d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a21d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a28d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a28d64s8k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a32d64s2k2z4c_1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a32d64s4k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a32d64s4k2z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLBuffer_a32d64s5k2z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLCFromBeat_serial_tl_0_a64d64s8k8z8c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLDFromBeat_serial_tl_0_a64d64s8k8z8c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLDToBeat_serial_tl_0_a64d64s8k8z8c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLEFromBeat_serial_tl_0_a64d64s8k8z8c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLError.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLFragmenter_BootAddrReg.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLFragmenter_CLINT.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLFragmenter_PLIC.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLFragmenter_ScratchpadBank.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLFragmenter_TileClockGater.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLFragmenter_TileResetSetter.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLFragmenter_bootrom.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLInterconnectCoupler_cbus_to_bootrom.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLInterconnectCoupler_cbus_to_clint.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLInterconnectCoupler_cbus_to_plic.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLInterconnectCoupler_cbus_to_prci_ctrl.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLInterconnectCoupler_fbus_from_port_named_serial_tl_0_in.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLInterconnectCoupler_mbus_to_memory_controller_port_named_tl_mem.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLInterconnectCoupler_pbus_to_bootaddressreg.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLPLIC.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLRAM_ScratchpadBank.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLROM.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLSerdesser_serial_tl_0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLSourceShrinker.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLToAXI4.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLXbar_MasterXbar_RocketTile_i2_o1_a32d64s2k2z4c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLXbar_cbus_in_i2_o1_a28d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLXbar_cbus_out_i1_o6_a28d64s7k1z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLXbar_fbus_i2_o1_a32d64s5k2z4u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLXbar_mbus_i1_o2_a32d64s8k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLXbar_prcibus_i1_o2_a21d64s7k1z3u.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TLXbar_sbus_i2_o2_a32d64s6k2z4c.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TSIToTileLink.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TileClockGater.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TilePRCIDomain.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/TileResetSetter.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/UARTRx.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/UARTToSerial.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/UARTTx.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/XilinxNexysVideoMIG.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/XilinxNexysVideoMIGIsland.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/bootromClockSinkDomain.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/mem.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x102.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x104.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x106.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x108.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x117.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x118.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x119.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x120.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x40.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x79.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x81.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x82.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_2x83.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_8x72.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_8x79.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_8x8.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_flit_8x32.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/ram_sink_2x2.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/regfile_32x65.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/rf_31x64.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/rockettile_dcache_data_arrays_0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/rockettile_dcache_tag_array.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/rockettile_icache_data_arrays_0.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/rockettile_icache_data_arrays_1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/rockettile_icache_tag_array.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/sourceIdMap_16x8.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/table_512x1.sv
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/NexysVideoHarness.sv
}
read_verilog -library xil_defaultlib {
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/AnalogToUInt_1.v
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/GenericDigitalInIOCell.v
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/GenericDigitalOutIOCell.v
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/PowerOnResetFPGAOnly.v
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/UIntToAnalog_1.v
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig.top.mems.v
  /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/gen-collateral/plusarg_reader.v
}
read_ip -quiet /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode.xci
set_property used_in_implementation false [get_files -all /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_board.xdc]
set_property used_in_implementation false [get_files -all /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode.xdc]
set_property used_in_implementation false [get_files -all /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_late.xdc]
set_property used_in_implementation false [get_files -all /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip/harnessSysPLLNode/harnessSysPLLNode_ooc.xdc]

read_ip -quiet /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip/nexysvideomig/nexysvideomig.xci
set_property used_in_implementation false [get_files -all /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip/nexysvideomig/nexysvideomig/user_design/constraints/nexysvideomig.xdc]
set_property used_in_implementation false [get_files -all /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/obj/ip/nexysvideomig/nexysvideomig/user_design/constraints/nexysvideomig_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /bwrcq/C/junsun/nexys_video_chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-config.xdc
set_property used_in_implementation false [get_files /bwrcq/C/junsun/nexys_video_chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-config.xdc]

read_xdc /bwrcq/C/junsun/nexys_video_chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-master.xdc
set_property used_in_implementation false [get_files /bwrcq/C/junsun/nexys_video_chipyard/fpga/fpga-shells/xilinx/nexys_video/constraints/nexys-video-master.xdc]

read_xdc /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig.shell.sdc
set_property used_in_implementation false [get_files /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig.shell.sdc]

read_xdc /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig.shell.xdc
set_property used_in_implementation false [get_files /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig.shell.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /bwrcq/C/junsun/nexys_video_chipyard/fpga/generated-src/chipyard.fpga.nexysvideo.NexysVideoHarness.RocketNexysVideoConfig/NexysVideoHarness.srcs/utils_1/imports/synth_1/NexysVideoHarness.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top NexysVideoHarness -part xc7a200tsbg484-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef NexysVideoHarness.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file NexysVideoHarness_utilization_synth.rpt -pb NexysVideoHarness_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
