// Generated by CIRCT firtool-1.75.0
module ChipTop(	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44]
  input         tl_slave_0_a_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output        tl_slave_0_a_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output [2:0]  tl_slave_0_a_bits_opcode,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output [2:0]  tl_slave_0_a_bits_param,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output [2:0]  tl_slave_0_a_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output [3:0]  tl_slave_0_a_bits_source,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output [31:0] tl_slave_0_a_bits_address,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output [7:0]  tl_slave_0_a_bits_mask,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output [63:0] tl_slave_0_a_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output        tl_slave_0_a_bits_corrupt,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  output        tl_slave_0_d_ready,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input         tl_slave_0_d_valid,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input  [2:0]  tl_slave_0_d_bits_opcode,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input  [1:0]  tl_slave_0_d_bits_param,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input  [2:0]  tl_slave_0_d_bits_size,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input  [3:0]  tl_slave_0_d_bits_source,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input         tl_slave_0_d_bits_sink,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input         tl_slave_0_d_bits_denied,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input  [63:0] tl_slave_0_d_bits_data,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input         tl_slave_0_d_bits_corrupt,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:541:33]
  input         custom_boot,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output        uart_tsi_uart_txd,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:533:22]
  input         uart_tsi_uart_rxd,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:533:22]
  output        uart_tsi_dropped,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:533:22]
  output [3:0]  uart_tsi_tsi2tl_state,	// @[generators/chipyard/src/main/scala/iobinders/IOBinders.scala:533:22]
  input         reset_io,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:87:24]
  input         clock_uncore,	// @[generators/chipyard/src/main/scala/clocking/ClockBinders.scala:95:26]
  output        clock_tap,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output        serial_tl_0_in_ready,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         serial_tl_0_in_valid,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input  [31:0] serial_tl_0_in_bits_phit,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         serial_tl_0_out_ready,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output        serial_tl_0_out_valid,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  output [31:0] serial_tl_0_out_bits_phit,	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
  input         serial_tl_0_clock_in	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:196:23]
);

  wire        _iocell_serial_tl_0_in_valid_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_31_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_30_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_29_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_28_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_27_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_26_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_25_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_24_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_23_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_22_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_21_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_20_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_19_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_18_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_17_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_16_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_15_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_14_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_13_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_12_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_11_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_10_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_9_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_8_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_7_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_6_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_5_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_4_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_3_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_2_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_1_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_in_bits_phit_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_out_ready_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_serial_tl_0_out_bits_phit_31_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_30_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_29_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_28_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_27_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_26_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_25_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_24_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_23_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_22_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_21_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_20_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_19_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_18_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_17_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_16_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_15_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_14_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_13_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_12_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_11_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_10_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_9_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_8_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_7_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_6_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_5_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_4_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_3_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_2_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_1_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_out_bits_phit_pad;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  wire        _iocell_serial_tl_0_clock_in_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _iocell_custom_boot_i;	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  wire        _system_serial_tl_0_in_ready;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        _system_serial_tl_0_out_valid;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire [31:0] _system_serial_tl_0_out_bits_phit;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  wire        _system_clock_tap;	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  DigitalTop system (	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_clock (clock_uncore),
    .auto_chipyard_prcictrl_domain_reset_setter_clock_in_member_allClocks_uncore_reset (reset_io),
    .mem_tl_0_a_ready                                                                  (tl_slave_0_a_ready),
    .mem_tl_0_a_valid                                                                  (tl_slave_0_a_valid),
    .mem_tl_0_a_bits_opcode                                                            (tl_slave_0_a_bits_opcode),
    .mem_tl_0_a_bits_param                                                             (tl_slave_0_a_bits_param),
    .mem_tl_0_a_bits_size                                                              (tl_slave_0_a_bits_size),
    .mem_tl_0_a_bits_source                                                            (tl_slave_0_a_bits_source),
    .mem_tl_0_a_bits_address                                                           (tl_slave_0_a_bits_address),
    .mem_tl_0_a_bits_mask                                                              (tl_slave_0_a_bits_mask),
    .mem_tl_0_a_bits_data                                                              (tl_slave_0_a_bits_data),
    .mem_tl_0_a_bits_corrupt                                                           (tl_slave_0_a_bits_corrupt),
    .mem_tl_0_d_ready                                                                  (tl_slave_0_d_ready),
    .mem_tl_0_d_valid                                                                  (tl_slave_0_d_valid),
    .mem_tl_0_d_bits_opcode                                                            (tl_slave_0_d_bits_opcode),
    .mem_tl_0_d_bits_param                                                             (tl_slave_0_d_bits_param),
    .mem_tl_0_d_bits_size                                                              (tl_slave_0_d_bits_size),
    .mem_tl_0_d_bits_source                                                            (tl_slave_0_d_bits_source),
    .mem_tl_0_d_bits_sink                                                              (tl_slave_0_d_bits_sink),
    .mem_tl_0_d_bits_denied                                                            (tl_slave_0_d_bits_denied),
    .mem_tl_0_d_bits_data                                                              (tl_slave_0_d_bits_data),
    .mem_tl_0_d_bits_corrupt                                                           (tl_slave_0_d_bits_corrupt),
    .uart_tsi_io_uart_txd                                                              (uart_tsi_uart_txd),
    .uart_tsi_io_uart_rxd                                                              (uart_tsi_uart_rxd),
    .uart_tsi_io_dropped                                                               (uart_tsi_dropped),
    .uart_tsi_io_tsi2tl_state                                                          (uart_tsi_tsi2tl_state),
    .custom_boot                                                                       (_iocell_custom_boot_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .serial_tl_0_in_ready                                                              (_system_serial_tl_0_in_ready),
    .serial_tl_0_in_valid                                                              (_iocell_serial_tl_0_in_valid_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .serial_tl_0_in_bits_phit                                                          ({_iocell_serial_tl_0_in_bits_phit_31_i, _iocell_serial_tl_0_in_bits_phit_30_i, _iocell_serial_tl_0_in_bits_phit_29_i, _iocell_serial_tl_0_in_bits_phit_28_i, _iocell_serial_tl_0_in_bits_phit_27_i, _iocell_serial_tl_0_in_bits_phit_26_i, _iocell_serial_tl_0_in_bits_phit_25_i, _iocell_serial_tl_0_in_bits_phit_24_i, _iocell_serial_tl_0_in_bits_phit_23_i, _iocell_serial_tl_0_in_bits_phit_22_i, _iocell_serial_tl_0_in_bits_phit_21_i, _iocell_serial_tl_0_in_bits_phit_20_i, _iocell_serial_tl_0_in_bits_phit_19_i, _iocell_serial_tl_0_in_bits_phit_18_i, _iocell_serial_tl_0_in_bits_phit_17_i, _iocell_serial_tl_0_in_bits_phit_16_i, _iocell_serial_tl_0_in_bits_phit_15_i, _iocell_serial_tl_0_in_bits_phit_14_i, _iocell_serial_tl_0_in_bits_phit_13_i, _iocell_serial_tl_0_in_bits_phit_12_i, _iocell_serial_tl_0_in_bits_phit_11_i, _iocell_serial_tl_0_in_bits_phit_10_i, _iocell_serial_tl_0_in_bits_phit_9_i, _iocell_serial_tl_0_in_bits_phit_8_i, _iocell_serial_tl_0_in_bits_phit_7_i, _iocell_serial_tl_0_in_bits_phit_6_i, _iocell_serial_tl_0_in_bits_phit_5_i, _iocell_serial_tl_0_in_bits_phit_4_i, _iocell_serial_tl_0_in_bits_phit_3_i, _iocell_serial_tl_0_in_bits_phit_2_i, _iocell_serial_tl_0_in_bits_phit_1_i, _iocell_serial_tl_0_in_bits_phit_i}),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23, :295:32]
    .serial_tl_0_out_ready                                                             (_iocell_serial_tl_0_out_ready_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .serial_tl_0_out_valid                                                             (_system_serial_tl_0_out_valid),
    .serial_tl_0_out_bits_phit                                                         (_system_serial_tl_0_out_bits_phit),
    .serial_tl_0_clock_in                                                              (_iocell_serial_tl_0_clock_in_i),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .clock_tap                                                                         (_system_clock_tap)
  );	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
  GenericDigitalInIOCell iocell_custom_boot (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (custom_boot),
    .i   (_iocell_custom_boot_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_clock_tap (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (clock_tap),
    .o   (_system_clock_tap),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalInIOCell iocell_serial_tl_0_clock_in (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_clock_in),
    .i   (_iocell_serial_tl_0_clock_in_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_pad),
    .o   (_system_serial_tl_0_out_bits_phit[0]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_1 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_1_pad),
    .o   (_system_serial_tl_0_out_bits_phit[1]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_2 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_2_pad),
    .o   (_system_serial_tl_0_out_bits_phit[2]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_3 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_3_pad),
    .o   (_system_serial_tl_0_out_bits_phit[3]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_4 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_4_pad),
    .o   (_system_serial_tl_0_out_bits_phit[4]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_5 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_5_pad),
    .o   (_system_serial_tl_0_out_bits_phit[5]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_6 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_6_pad),
    .o   (_system_serial_tl_0_out_bits_phit[6]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_7 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_7_pad),
    .o   (_system_serial_tl_0_out_bits_phit[7]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_8 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_8_pad),
    .o   (_system_serial_tl_0_out_bits_phit[8]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_9 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_9_pad),
    .o   (_system_serial_tl_0_out_bits_phit[9]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_10 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_10_pad),
    .o   (_system_serial_tl_0_out_bits_phit[10]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_11 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_11_pad),
    .o   (_system_serial_tl_0_out_bits_phit[11]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_12 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_12_pad),
    .o   (_system_serial_tl_0_out_bits_phit[12]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_13 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_13_pad),
    .o   (_system_serial_tl_0_out_bits_phit[13]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_14 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_14_pad),
    .o   (_system_serial_tl_0_out_bits_phit[14]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_15 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_15_pad),
    .o   (_system_serial_tl_0_out_bits_phit[15]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_16 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_16_pad),
    .o   (_system_serial_tl_0_out_bits_phit[16]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_17 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_17_pad),
    .o   (_system_serial_tl_0_out_bits_phit[17]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_18 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_18_pad),
    .o   (_system_serial_tl_0_out_bits_phit[18]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_19 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_19_pad),
    .o   (_system_serial_tl_0_out_bits_phit[19]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_20 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_20_pad),
    .o   (_system_serial_tl_0_out_bits_phit[20]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_21 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_21_pad),
    .o   (_system_serial_tl_0_out_bits_phit[21]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_22 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_22_pad),
    .o   (_system_serial_tl_0_out_bits_phit[22]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_23 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_23_pad),
    .o   (_system_serial_tl_0_out_bits_phit[23]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_24 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_24_pad),
    .o   (_system_serial_tl_0_out_bits_phit[24]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_25 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_25_pad),
    .o   (_system_serial_tl_0_out_bits_phit[25]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_26 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_26_pad),
    .o   (_system_serial_tl_0_out_bits_phit[26]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_27 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_27_pad),
    .o   (_system_serial_tl_0_out_bits_phit[27]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_28 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_28_pad),
    .o   (_system_serial_tl_0_out_bits_phit[28]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_29 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_29_pad),
    .o   (_system_serial_tl_0_out_bits_phit[29]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_30 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_30_pad),
    .o   (_system_serial_tl_0_out_bits_phit[30]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_bits_phit_31 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (_iocell_serial_tl_0_out_bits_phit_31_pad),
    .o   (_system_serial_tl_0_out_bits_phit[31]),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35, generators/chipyard/src/main/scala/iocell/IOCell.scala:299:40]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalOutIOCell iocell_serial_tl_0_out_valid (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (serial_tl_0_out_valid),
    .o   (_system_serial_tl_0_out_valid),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  GenericDigitalInIOCell iocell_serial_tl_0_out_ready (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_out_ready),
    .i   (_iocell_serial_tl_0_out_ready_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[0]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_1 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[1]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_1_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_2 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[2]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_2_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_3 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[3]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_3_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_4 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[4]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_4_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_5 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[5]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_5_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_6 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[6]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_6_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_7 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[7]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_7_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_8 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[8]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_8_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_9 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[9]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_9_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_10 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[10]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_10_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_11 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[11]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_11_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_12 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[12]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_12_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_13 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[13]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_13_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_14 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[14]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_14_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_15 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[15]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_15_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_16 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[16]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_16_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_17 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[17]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_17_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_18 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[18]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_18_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_19 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[19]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_19_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_20 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[20]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_20_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_21 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[21]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_21_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_22 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[22]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_22_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_23 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[23]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_23_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_24 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[24]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_24_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_25 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[25]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_25_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_26 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[26]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_26_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_27 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[27]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_27_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_28 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[28]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_28_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_29 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[29]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_29_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_30 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[30]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_30_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_bits_phit_31 (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_bits_phit[31]),	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:282:39]
    .i   (_iocell_serial_tl_0_in_bits_phit_31_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalInIOCell iocell_serial_tl_0_in_valid (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
    .pad (serial_tl_0_in_valid),
    .i   (_iocell_serial_tl_0_in_valid_i),
    .ie  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:176:23]
  GenericDigitalOutIOCell iocell_serial_tl_0_in_ready (	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
    .pad (serial_tl_0_in_ready),
    .o   (_system_serial_tl_0_in_ready),	// @[generators/chipyard/src/main/scala/ChipTop.scala:27:35]
    .oe  (1'h1)
  );	// @[generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24]
  assign serial_tl_0_out_bits_phit = {_iocell_serial_tl_0_out_bits_phit_31_pad, _iocell_serial_tl_0_out_bits_phit_30_pad, _iocell_serial_tl_0_out_bits_phit_29_pad, _iocell_serial_tl_0_out_bits_phit_28_pad, _iocell_serial_tl_0_out_bits_phit_27_pad, _iocell_serial_tl_0_out_bits_phit_26_pad, _iocell_serial_tl_0_out_bits_phit_25_pad, _iocell_serial_tl_0_out_bits_phit_24_pad, _iocell_serial_tl_0_out_bits_phit_23_pad, _iocell_serial_tl_0_out_bits_phit_22_pad, _iocell_serial_tl_0_out_bits_phit_21_pad, _iocell_serial_tl_0_out_bits_phit_20_pad, _iocell_serial_tl_0_out_bits_phit_19_pad, _iocell_serial_tl_0_out_bits_phit_18_pad, _iocell_serial_tl_0_out_bits_phit_17_pad, _iocell_serial_tl_0_out_bits_phit_16_pad, _iocell_serial_tl_0_out_bits_phit_15_pad, _iocell_serial_tl_0_out_bits_phit_14_pad, _iocell_serial_tl_0_out_bits_phit_13_pad, _iocell_serial_tl_0_out_bits_phit_12_pad, _iocell_serial_tl_0_out_bits_phit_11_pad, _iocell_serial_tl_0_out_bits_phit_10_pad, _iocell_serial_tl_0_out_bits_phit_9_pad, _iocell_serial_tl_0_out_bits_phit_8_pad, _iocell_serial_tl_0_out_bits_phit_7_pad, _iocell_serial_tl_0_out_bits_phit_6_pad, _iocell_serial_tl_0_out_bits_phit_5_pad, _iocell_serial_tl_0_out_bits_phit_4_pad, _iocell_serial_tl_0_out_bits_phit_3_pad, _iocell_serial_tl_0_out_bits_phit_2_pad, _iocell_serial_tl_0_out_bits_phit_1_pad, _iocell_serial_tl_0_out_bits_phit_pad};	// @[generators/chipyard/src/main/scala/ChipTop.scala:33:44, generators/chipyard/src/main/scala/iocell/IOCell.scala:177:24, :312:31]
endmodule

