// Generated by CIRCT firtool-1.75.0
module CoherenceManagerWrapper(	// @[generators/rocket-chip/src/main/scala/prci/ClockDomain.scala:14:9]
  input         auto_coupler_to_bus_named_mbus_bus_xing_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_bus_named_mbus_bus_xing_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coupler_to_bus_named_mbus_bus_xing_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_bus_named_mbus_bus_xing_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coherent_jbar_anon_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coherent_jbar_anon_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coherent_jbar_anon_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coherent_jbar_anon_in_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coherent_jbar_anon_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [5:0]  auto_coherent_jbar_anon_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coherent_jbar_anon_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_coherent_jbar_anon_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_coherent_jbar_anon_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coherent_jbar_anon_in_b_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coherent_jbar_anon_in_b_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_coherent_jbar_anon_in_b_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_coherent_jbar_anon_in_b_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coherent_jbar_anon_in_c_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coherent_jbar_anon_in_c_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coherent_jbar_anon_in_c_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coherent_jbar_anon_in_c_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_coherent_jbar_anon_in_c_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [5:0]  auto_coherent_jbar_anon_in_c_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [31:0] auto_coherent_jbar_anon_in_c_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_coherent_jbar_anon_in_c_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coherent_jbar_anon_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coherent_jbar_anon_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coherent_jbar_anon_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_coherent_jbar_anon_in_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_coherent_jbar_anon_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [5:0]  auto_coherent_jbar_anon_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_coherent_jbar_anon_in_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coherent_jbar_anon_in_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_coherent_jbar_anon_in_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_coherent_jbar_anon_in_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coherent_jbar_anon_in_e_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_coherent_jbar_anon_in_e_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coh_clock_groups_in_member_coh_0_clock,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_coh_clock_groups_in_member_coh_0_reset	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire        _binder_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire        _binder_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire [2:0]  _binder_auto_in_d_bits_opcode;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire [1:0]  _binder_auto_in_d_bits_param;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire [2:0]  _binder_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire [7:0]  _binder_auto_in_d_bits_source;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire        _binder_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire [63:0] _binder_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire        _binder_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  wire        _broadcast_1_auto_out_a_valid;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  wire [2:0]  _broadcast_1_auto_out_a_bits_opcode;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  wire [2:0]  _broadcast_1_auto_out_a_bits_param;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  wire [2:0]  _broadcast_1_auto_out_a_bits_size;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  wire [7:0]  _broadcast_1_auto_out_a_bits_source;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  wire [31:0] _broadcast_1_auto_out_a_bits_address;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  wire [7:0]  _broadcast_1_auto_out_a_bits_mask;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  wire [63:0] _broadcast_1_auto_out_a_bits_data;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  wire        _broadcast_1_auto_out_d_ready;	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  TLBroadcast broadcast_1 (	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .clock                   (auto_coh_clock_groups_in_member_coh_0_clock),
    .reset                   (auto_coh_clock_groups_in_member_coh_0_reset),
    .auto_in_a_ready         (auto_coherent_jbar_anon_in_a_ready),
    .auto_in_a_valid         (auto_coherent_jbar_anon_in_a_valid),
    .auto_in_a_bits_opcode   (auto_coherent_jbar_anon_in_a_bits_opcode),
    .auto_in_a_bits_param    (auto_coherent_jbar_anon_in_a_bits_param),
    .auto_in_a_bits_size     (auto_coherent_jbar_anon_in_a_bits_size),
    .auto_in_a_bits_source   (auto_coherent_jbar_anon_in_a_bits_source),
    .auto_in_a_bits_address  (auto_coherent_jbar_anon_in_a_bits_address),
    .auto_in_a_bits_mask     (auto_coherent_jbar_anon_in_a_bits_mask),
    .auto_in_a_bits_data     (auto_coherent_jbar_anon_in_a_bits_data),
    .auto_in_b_ready         (auto_coherent_jbar_anon_in_b_ready),
    .auto_in_b_valid         (auto_coherent_jbar_anon_in_b_valid),
    .auto_in_b_bits_param    (auto_coherent_jbar_anon_in_b_bits_param),
    .auto_in_b_bits_address  (auto_coherent_jbar_anon_in_b_bits_address),
    .auto_in_c_ready         (auto_coherent_jbar_anon_in_c_ready),
    .auto_in_c_valid         (auto_coherent_jbar_anon_in_c_valid),
    .auto_in_c_bits_opcode   (auto_coherent_jbar_anon_in_c_bits_opcode),
    .auto_in_c_bits_param    (auto_coherent_jbar_anon_in_c_bits_param),
    .auto_in_c_bits_size     (auto_coherent_jbar_anon_in_c_bits_size),
    .auto_in_c_bits_source   (auto_coherent_jbar_anon_in_c_bits_source),
    .auto_in_c_bits_address  (auto_coherent_jbar_anon_in_c_bits_address),
    .auto_in_c_bits_data     (auto_coherent_jbar_anon_in_c_bits_data),
    .auto_in_d_ready         (auto_coherent_jbar_anon_in_d_ready),
    .auto_in_d_valid         (auto_coherent_jbar_anon_in_d_valid),
    .auto_in_d_bits_opcode   (auto_coherent_jbar_anon_in_d_bits_opcode),
    .auto_in_d_bits_param    (auto_coherent_jbar_anon_in_d_bits_param),
    .auto_in_d_bits_size     (auto_coherent_jbar_anon_in_d_bits_size),
    .auto_in_d_bits_source   (auto_coherent_jbar_anon_in_d_bits_source),
    .auto_in_d_bits_sink     (auto_coherent_jbar_anon_in_d_bits_sink),
    .auto_in_d_bits_denied   (auto_coherent_jbar_anon_in_d_bits_denied),
    .auto_in_d_bits_data     (auto_coherent_jbar_anon_in_d_bits_data),
    .auto_in_d_bits_corrupt  (auto_coherent_jbar_anon_in_d_bits_corrupt),
    .auto_in_e_valid         (auto_coherent_jbar_anon_in_e_valid),
    .auto_in_e_bits_sink     (auto_coherent_jbar_anon_in_e_bits_sink),
    .auto_out_a_ready        (_binder_auto_in_a_ready),	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_out_a_valid        (_broadcast_1_auto_out_a_valid),
    .auto_out_a_bits_opcode  (_broadcast_1_auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (_broadcast_1_auto_out_a_bits_param),
    .auto_out_a_bits_size    (_broadcast_1_auto_out_a_bits_size),
    .auto_out_a_bits_source  (_broadcast_1_auto_out_a_bits_source),
    .auto_out_a_bits_address (_broadcast_1_auto_out_a_bits_address),
    .auto_out_a_bits_mask    (_broadcast_1_auto_out_a_bits_mask),
    .auto_out_a_bits_data    (_broadcast_1_auto_out_a_bits_data),
    .auto_out_d_ready        (_broadcast_1_auto_out_d_ready),
    .auto_out_d_valid        (_binder_auto_in_d_valid),	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_out_d_bits_opcode  (_binder_auto_in_d_bits_opcode),	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_out_d_bits_param   (_binder_auto_in_d_bits_param),	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_out_d_bits_size    (_binder_auto_in_d_bits_size),	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_out_d_bits_source  (_binder_auto_in_d_bits_source),	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_out_d_bits_denied  (_binder_auto_in_d_bits_denied),	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_out_d_bits_data    (_binder_auto_in_d_bits_data),	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_out_d_bits_corrupt (_binder_auto_in_d_bits_corrupt)	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
  );	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
  BankBinder binder (	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
    .auto_in_a_ready         (_binder_auto_in_a_ready),
    .auto_in_a_valid         (_broadcast_1_auto_out_a_valid),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_a_bits_opcode   (_broadcast_1_auto_out_a_bits_opcode),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_a_bits_param    (_broadcast_1_auto_out_a_bits_param),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_a_bits_size     (_broadcast_1_auto_out_a_bits_size),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_a_bits_source   (_broadcast_1_auto_out_a_bits_source),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_a_bits_address  (_broadcast_1_auto_out_a_bits_address),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_a_bits_mask     (_broadcast_1_auto_out_a_bits_mask),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_a_bits_data     (_broadcast_1_auto_out_a_bits_data),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_d_ready         (_broadcast_1_auto_out_d_ready),	// @[generators/rocket-chip/src/main/scala/subsystem/BankedCoherenceParams.scala:90:24]
    .auto_in_d_valid         (_binder_auto_in_d_valid),
    .auto_in_d_bits_opcode   (_binder_auto_in_d_bits_opcode),
    .auto_in_d_bits_param    (_binder_auto_in_d_bits_param),
    .auto_in_d_bits_size     (_binder_auto_in_d_bits_size),
    .auto_in_d_bits_source   (_binder_auto_in_d_bits_source),
    .auto_in_d_bits_denied   (_binder_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_binder_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_binder_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (auto_coupler_to_bus_named_mbus_bus_xing_out_a_ready),
    .auto_out_a_valid        (auto_coupler_to_bus_named_mbus_bus_xing_out_a_valid),
    .auto_out_a_bits_opcode  (auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_opcode),
    .auto_out_a_bits_param   (auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_param),
    .auto_out_a_bits_size    (auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_size),
    .auto_out_a_bits_source  (auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_source),
    .auto_out_a_bits_address (auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_address),
    .auto_out_a_bits_mask    (auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_mask),
    .auto_out_a_bits_data    (auto_coupler_to_bus_named_mbus_bus_xing_out_a_bits_data),
    .auto_out_d_ready        (auto_coupler_to_bus_named_mbus_bus_xing_out_d_ready),
    .auto_out_d_valid        (auto_coupler_to_bus_named_mbus_bus_xing_out_d_valid),
    .auto_out_d_bits_opcode  (auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_opcode),
    .auto_out_d_bits_param   (auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_param),
    .auto_out_d_bits_size    (auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_size),
    .auto_out_d_bits_source  (auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_source),
    .auto_out_d_bits_denied  (auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_denied),
    .auto_out_d_bits_data    (auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_data),
    .auto_out_d_bits_corrupt (auto_coupler_to_bus_named_mbus_bus_xing_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/BankBinder.scala:71:28]
endmodule

