// Generated by CIRCT firtool-1.75.0
module SerialWidthAdapter(	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:50:7]
  input         clock,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:50:7]
  input         reset,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:50:7]
  output        io_narrow_in_ready,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  input         io_narrow_in_valid,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  input  [7:0]  io_narrow_in_bits,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  input         io_narrow_out_ready,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  output        io_narrow_out_valid,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  output [7:0]  io_narrow_out_bits,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  output        io_wide_in_ready,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  input         io_wide_in_valid,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  input  [31:0] io_wide_in_bits,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  input         io_wide_out_ready,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  output        io_wide_out_valid,	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
  output [31:0] io_wide_out_bits	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:53:14]
);

  SerialWidthAggregator aggregator (	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:58:26]
    .clock           (clock),
    .reset           (reset),
    .io_narrow_ready (io_narrow_in_ready),
    .io_narrow_valid (io_narrow_in_valid),
    .io_narrow_bits  (io_narrow_in_bits),
    .io_wide_ready   (io_wide_out_ready),
    .io_wide_valid   (io_wide_out_valid),
    .io_wide_bits    (io_wide_out_bits)
  );	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:58:26]
  SerialWidthSlicer slicer (	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:62:22]
    .clock           (clock),
    .reset           (reset),
    .io_wide_ready   (io_wide_in_ready),
    .io_wide_valid   (io_wide_in_valid),
    .io_wide_bits    (io_wide_in_bits),
    .io_narrow_ready (io_narrow_out_ready),
    .io_narrow_valid (io_narrow_out_valid),
    .io_narrow_bits  (io_narrow_out_bits)
  );	// @[generators/testchipip/src/main/scala/serdes/Adapter.scala:62:22]
endmodule

