// Generated by CIRCT firtool-1.75.0
// VCS coverage exclude_file
module sourceIdMap_16x8(	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
  input  [3:0] R0_addr,
  input        R0_en,
  input        R0_clk,
  output [7:0] R0_data,
  input  [3:0] W0_addr,
  input        W0_en,
  input        W0_clk,
  input  [7:0] W0_data
);

  reg [7:0] Memory[0:15];	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
  always @(posedge W0_clk) begin	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
    if (W0_en & 1'h1)	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
      Memory[W0_addr] <= W0_data;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
    reg [31:0] _RANDOM_MEM;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
    initial begin	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
      `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
      `ifdef RANDOMIZE_MEM_INIT	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
        for (logic [4:0] i = 5'h0; i < 5'h10; i += 5'h1) begin
          _RANDOM_MEM = `RANDOM;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
          Memory[i[3:0]] = _RANDOM_MEM[7:0];	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 8'bx;	// @[generators/rocket-chip/src/main/scala/tilelink/SourceShrinker.scala:58:30]
endmodule

