// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module TLPLIC(	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  input         clock,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  input         reset,	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
  output        auto_in_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_in_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_in_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [10:0] auto_in_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [27:0] auto_in_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [7:0]  auto_in_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_in_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_in_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_in_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_in_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [1:0]  auto_in_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [10:0] auto_in_d_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_in_d_bits_data	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
);

  wire        _out_rofireMux_T_1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_6;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        out_backSel_4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_0;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        claimer_1;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_back_front_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire        _out_back_front_q_io_deq_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [22:0] _out_back_front_q_io_deq_bits_index;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [7:0]  _out_back_front_q_io_deq_bits_mask;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
    wire [1:0] _GEN = {claimer_1, claimer_0};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:21, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
      if (~reset & (|(_GEN & _GEN - 2'h1))) begin	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:{11,21,28,46,54}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
          $error("Assertion failed\n    at Plic.scala:249 assert((claimer.asUInt & (claimer.asUInt - 1.U)) === 0.U) // One-Hot\n");	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
          $fatal;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:249:11]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _out_T_9 = {_out_back_front_q_io_deq_bits_index[22:19], _out_back_front_q_io_deq_bits_index[17:10], _out_back_front_q_io_deq_bits_index[8:5], _out_back_front_q_io_deq_bits_index[3:0]} == 20'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [31:0] _out_womask_T_7 = {{8{_out_back_front_q_io_deq_bits_mask[7]}}, {8{_out_back_front_q_io_deq_bits_mask[6]}}, {8{_out_back_front_q_io_deq_bits_mask[5]}}, {8{_out_back_front_q_io_deq_bits_mask[4]}}};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign claimer_1 = _out_rofireMux_T_1 & out_backSel_6 & _out_T_9 & (|_out_womask_T_7);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign claimer_0 = _out_rofireMux_T_1 & out_backSel_4 & _out_T_9 & (|_out_womask_T_7);	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  wire [2:0]  _GEN_0 = {_out_back_front_q_io_deq_bits_index[18], _out_back_front_q_io_deq_bits_index[9], _out_back_front_q_io_deq_bits_index[4]};	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_4 = _GEN_0 == 3'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign out_backSel_6 = _GEN_0 == 3'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, src/main/scala/chisel3/util/OneHot.scala:58:35]
  assign _out_rofireMux_T_1 = _out_back_front_q_io_deq_valid & auto_in_d_ready & _out_back_front_q_io_deq_bits_read;	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  Queue1_RegMapperInput_i23_m8 out_back_front_q (	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
    .clock                               (clock),
    .reset                               (reset),
    .io_enq_ready                        (auto_in_a_ready),
    .io_enq_valid                        (auto_in_a_valid),
    .io_enq_bits_read                    (auto_in_a_bits_opcode == 3'h4),	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:74:36]
    .io_enq_bits_index                   (auto_in_a_bits_address[25:3]),	// @[generators/rocket-chip/src/main/scala/tilelink/Edges.scala:192:34, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:75:19]
    .io_enq_bits_data                    (auto_in_a_bits_data),
    .io_enq_bits_mask                    (auto_in_a_bits_mask),
    .io_enq_bits_extra_tlrr_extra_source (auto_in_a_bits_source),
    .io_enq_bits_extra_tlrr_extra_size   (auto_in_a_bits_size),
    .io_deq_ready                        (auto_in_d_ready),
    .io_deq_valid                        (_out_back_front_q_io_deq_valid),
    .io_deq_bits_read                    (_out_back_front_q_io_deq_bits_read),
    .io_deq_bits_index                   (_out_back_front_q_io_deq_bits_index),
    .io_deq_bits_mask                    (_out_back_front_q_io_deq_bits_mask),
    .io_deq_bits_extra_tlrr_extra_source (auto_in_d_bits_source),
    .io_deq_bits_extra_tlrr_extra_size   (auto_in_d_bits_size)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_valid = _out_back_front_q_io_deq_valid;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24]
  assign auto_in_d_bits_opcode = {2'h0, _out_back_front_q_io_deq_bits_read};	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9, generators/rocket-chip/src/main/scala/tilelink/RegisterRouter.scala:87:24, :105:19]
  assign auto_in_d_bits_data = 64'h0;	// @[generators/rocket-chip/src/main/scala/devices/tilelink/Plic.scala:132:9]
endmodule

