set_property PACKAGE_PIN {R4} [get_ports {sys_clock}]
set_property IOSTANDARD {LVCMOS33} [get_ports {sys_clock}]
set_property PACKAGE_PIN {V18} [get_ports {uart_rxd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_rxd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_rxd}]]]
set_property PACKAGE_PIN {AA19} [get_ports {uart_txd}]
set_property IOSTANDARD {LVCMOS33} [get_ports {uart_txd}]
set_property IOB {TRUE} [ get_cells -of_objects [ all_fanin -flat -startpoints_only [get_ports {uart_txd}]]]
set_property PACKAGE_PIN {T14} [get_ports {led_0}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_0}]
set_property PACKAGE_PIN {T15} [get_ports {led_1}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_1}]
set_property PACKAGE_PIN {T16} [get_ports {led_2}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_2}]
set_property PACKAGE_PIN {U16} [get_ports {led_3}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_3}]
set_property PACKAGE_PIN {V15} [get_ports {led_4}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_4}]
set_property PACKAGE_PIN {W16} [get_ports {led_5}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_5}]
set_property PACKAGE_PIN {W15} [get_ports {led_6}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_6}]
set_property PACKAGE_PIN {Y13} [get_ports {led_7}]
set_property IOSTANDARD {LVCMOS33} [get_ports {led_7}]
set_property BOARD_PIN {reset} [get_ports {reset}]
